version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      #time: "11:00" # default is random time
      #timezone: "Europe/Budapest"

    # default is default branch
    # target-branch: "branch"

    # Disable version updates for dependencies
    open-pull-requests-limit: 0
    reviewers:
      - "Strivacity/security-reviewers"
